site_name: CPSLab

theme:
    name: material
    logo: img/csirlogo.png

nav:
  - Home: index.md
  - The Sojourner: autonomous.md
  - The Phenonet Testbed: pheno.md

markdown_extensions:
  - attr_list
  - md_in_html

plugins:
    - search
